import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/utils/utils";
import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";
import ConvexClientProvider from "./ConvexClientProvider";
import { Provider } from "react-wrap-balancer";
import "./globals.css";
import { CartProvider } from "@/components/CartContex";

const fontSans = FontSans({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-sans",
  fallback: ["Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "fibonacci",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full !scroll-smooth">
      <body
        className={cn(
          "relative h-full font-sans antialiased",
          fontSans.variable,
        )}
      >
        {/* bg-[url('/bg2.png')] */}
        <main className="relative flex min-h-screen flex-col bg-cover bg-no-repeat">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <CartProvider> */}
            <div className="flex-1 flex-grow">
              <ConvexClientProvider>
                <Provider>
                  <Navbar />
                  {children}
                  <Toaster />
                  <Footer />
                </Provider>
              </ConvexClientProvider>
            </div>
            {/* </CartProvider> */}
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
